### ISSUE TITLE
Setup fails when some workflows are already installed

### ISSUE THREAD

**Issue by denis-yuen** [ICGC-TCGA-PanCancer/container-host-bag#7]
The task which downloads workflows reports changed only once. 
Thus when we try to set bundle permissions, we set them not only on what downloaded but what may previously have been downloaded (and the zip cleaned up already).

This will fail.

**Comment by denis-yuen** [comment]
In the node in question, we had HelloWorld 1.1.1 installed, not 1.1.0

```
TASK: [workflow | Download workflows] ***************************************** 
skipping: [i-b03b9c1a] => (item=Workflow_Bundle_BWA_2.6.1_SeqWare_1.1.0-alpha.5)
changed: [i-b03b9c1a] => (item=Workflow_Bundle_HelloWorld_1.0-SNAPSHOT_SeqWare_1.1.0)

TASK: [workflow | Setup bundle permissions] *********************************** 
failed: [i-b03b9c1a] => (item=Workflow_Bundle_BWA_2.6.1_SeqWare_1.1.0-alpha.5) => {"failed": true, "item": "Workflow_Bundle_BWA_2.6.1_SeqWare_1.1.0-alpha.5", "path": "/workflows/Workflow_Bundle_BWA_2.6.1_SeqWare_1.1.0-alpha.5.zip", "state": "absent"}
msg: file (/workflows/Workflow_Bundle_BWA_2.6.1_SeqWare_1.1.0-alpha.5.zip) is absent, cannot continue
ok: [i-b03b9c1a] => (item=Workflow_Bundle_HelloWorld_1.0-SNAPSHOT_SeqWare_1.1.0)

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
          to retry, use: --limit @/home/ubuntu/install.retry

i-b03b9c1a                 : ok=47   changed=21   unreachable=0    failed=1  

22:09:59,588 ERROR ovisioner.ContainerProvisionerThreads$ProvisionVMs: 224 - Youxia deployer threw the following exception
java.lang.RuntimeException: org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)
       at io.cloudbindle.youxia.deployer.Deployer.runAnsible(Deployer.java:490)
       at io.cloudbindle.youxia.deployer.Deployer.runAnsible(Deployer.java:421)
       at io.cloudbindle.youxia.deployer.Deployer.runDeployment(Deployer.java:551)
       at io.cloudbindle.youxia.deployer.Deployer.main(Deployer.java:593)
       at info.pancancer.arch3.containerProvisioner.ContainerProvisionerThreads$ProvisionVMs.call(ContainerProvisionerThreads.java:222)
       at info.pancancer.arch3.containerProvisioner.ContainerProvisionerThreads$ProvisionVMs.call(ContainerProvisionerThreads.java:155)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
       at java.util.concurrent.FutureTask.run(FutureTask.java:166)
```

**Comment by SolomonShorser-OICR** [comment]
The condition for the "Setup bundle permissions" play could be changed to match the condition in the "Download workflows" play:

`when: '"{{ item }}" not in provisioned_bundles.stdout'`

I haven't tried this out yet (I'll give it a try later on), but it looks like Ansible tried to set up the permissions on the BWA bundle because it was not "changed", it was "skipping". But the original condition in the failing play is:

`when: workflows_downloaded.changed`

and it's failing probably because there's no way to know _which_ file was downloaded when the other play executed.
